import Head from 'next/head';
import AboutService from '../src/Components/aboutService/AboutService';
import HomeAdditional from '../src/Components/homeAdditional/HomeAdditional';

import Layout from '../src/Components/layout/layout';

export default function Home() {
	return (
		<>
			<Head>
				<title>Hydroengeo</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<AboutService />
				<HomeAdditional />
			</Layout>
		</>
	);
}
